// Org-graph types — the shape of src/data/org-graph.json (generated by
// scripts/gen-org-graph.mjs from icm/org.yaml + icm/**) plus the live-state overlay
// the /org page (#1539) reads from Postgres at request time.

export type OrgNodeKind = "orchestrator" | "executive" | "domain";

export interface OrgWorkflow {
  slug: string;
  stages: string[];
}

export interface OrgNode {
  id: string;
  kind: OrgNodeKind;
  persona: string | null;
  reportsTo: string | null;
  /** The human (humans[].key) this agent ultimately answers to; may differ from
   *  its agent-manager's human (a deliberate hybrid). */
  humanManager: string | null;
  ceiling: string | null;
  serves: string | null;
  division: string | null;
  /** Public-render fields (the org chart is classified public-approved). */
  title: string | null;
  summary: string | null;
  built: boolean;
  /** Executives only: the domain slugs in their division. */
  memberDomains: string[];
  tools: string[];
  okfRooms: string[];
  workflows: OrgWorkflow[];
}

export interface OrgEdge {
  from: string;
  to: string;
}

/** A real staff member — the human org layer the agent tree reports up into. */
export interface OrgHuman {
  key: string;
  name: string | null;
  role: string | null;
  title: string | null;
  summary: string | null;
  /** Another human's key, or null for the top of the human org (Derek). */
  reportsTo: string | null;
}

export interface OrgGraph {
  orchestrator: string;
  nodes: OrgNode[];
  edges: OrgEdge[];
  /** The 7 real staff; agents point in via OrgNode.humanManager. */
  humans: OrgHuman[];
}

// ── Procedure + step detail (src/data/agent-procedures.json, #1612) ──────────
// The full per-agent playbook surface the /org/[agentId] page renders. Generated
// from each workflow's agent.yaml + CONTEXT.md + stages/**/CONTEXT.md by
// scripts/gen-org-graph.mjs. Kept separate from OrgGraph + loaded server-side only
// (it is ~600KB of prose) so it never enters the /org client bundle.

/** One numbered Process step, with its `[script]/[haiku]/[sonnet]` execution tag. */
export interface ProcedureStep {
  /** The execution tier — `script` (deterministic), `haiku`, `sonnet`, etc.; null if untagged. */
  tag: string | null;
  text: string;
}

/** A render-ready markdown pipe-table (the stage Inputs contract). */
export interface ProcedureTable {
  headers: string[];
  rows: string[][];
}

/** One stage = one step-group in a procedure (the stages/NN/CONTEXT.md contract). */
export interface ProcedureStage {
  slug: string;
  name: string;
  job: string | null;
  process: ProcedureStep[];
  inputs: ProcedureTable;
  outputs: string | null;
  audit: string[];
  /** The human-approval contract at a checkpoint stage, or null when there is none. */
  checkpoint: string | null;
}

/** One procedure = one workflow: its settings (manifest) + ordered stages. */
export interface Procedure {
  slug: string;
  title: string;
  job: string | null;
  trigger: string | null;
  model: string | null;
  /** ICM autonomy ceiling for `auto` mode (L0–L3). */
  autonomyRung: string | null;
  /** Prose statement of what `auto` may self-approve at this rung (everything else parks). */
  autoMaySelfApprove: string | null;
  tools: string[];
  okfRooms: string[];
  skills: string[];
  stages: ProcedureStage[];
}

export interface AgentProcedures {
  id: string;
  persona: string | null;
  kind: OrgNodeKind;
  procedures: Procedure[];
}

export interface AgentProceduresFile {
  agents: Record<string, AgentProcedures>;
}

/** Per-agent live state, keyed by `agent_key` (best-effort matched to a node id/persona). */
export interface OrgNodeLive {
  /** Highest ICM autonomy rung on record (L0–L3) across the agent's workflows. */
  rung: string | null;
  /** Highest actuation-dial level on record (1–5). */
  level: number | null;
  /** Any always-gated / mark-gated leg on record. */
  gated: boolean;
  /** Pending approval-queue actions for this agent. */
  pending: number;
}

export interface OrgLiveState {
  /** Whether the DB was reachable; false = the overlay is dormant (skeleton only). */
  live: boolean;
  byKey: Record<string, OrgNodeLive>;
  summary: {
    runs7d: number;
    costUsd7d: number;
    pendingTotal: number;
  };
}
