// Org-graph types — the shape of src/data/org-graph.json (generated by
// scripts/gen-org-graph.mjs from icm/org.yaml + icm/**) plus the live-state overlay
// the /org page (#1539) reads from Postgres at request time.

export type OrgNodeKind = "orchestrator" | "executive" | "domain";

export interface OrgWorkflow {
  slug: string;
  stages: string[];
}

export interface OrgNode {
  id: string;
  kind: OrgNodeKind;
  persona: string | null;
  reportsTo: string | null;
  ceiling: string | null;
  serves: string | null;
  division: string | null;
  built: boolean;
  /** Executives only: the domain slugs in their division. */
  memberDomains: string[];
  tools: string[];
  okfRooms: string[];
  workflows: OrgWorkflow[];
}

export interface OrgEdge {
  from: string;
  to: string;
}

export interface OrgGraph {
  orchestrator: string;
  nodes: OrgNode[];
  edges: OrgEdge[];
}

/** Per-agent live state, keyed by `agent_key` (best-effort matched to a node id/persona). */
export interface OrgNodeLive {
  /** Highest ICM autonomy rung on record (L0–L3) across the agent's workflows. */
  rung: string | null;
  /** Highest actuation-dial level on record (1–5). */
  level: number | null;
  /** Any always-gated / mark-gated leg on record. */
  gated: boolean;
  /** Pending approval-queue actions for this agent. */
  pending: number;
}

export interface OrgLiveState {
  /** Whether the DB was reachable; false = the overlay is dormant (skeleton only). */
  live: boolean;
  byKey: Record<string, OrgNodeLive>;
  summary: {
    runs7d: number;
    costUsd7d: number;
    pendingTotal: number;
  };
}
